
#--incompatible_remove_native_git_repository=False

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

#load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")



#load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
#cpp_proto_repositories()

#load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

#workspace(name = "com_github_googlecartographer_async_grpc")

#load("//:bazel/repositories.bzl", "repositories")

#repositories()

#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#http_archive(
#)


