
#--incompatible_remove_native_git_repository=False

#load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

#git_repository(
#  name = "org_pubref_rules_protobuf",
#  remote = "https://github.com/pubref/rules_protobuf",
#  tag = "v0.8.1",
#)

#load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
#cpp_proto_repositories()

#load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")



#load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
#cpp_proto_repositories()

#load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

#workspace(name = "com_github_googlecartographer_async_grpc")

#load("//:bazel/repositories.bzl", "repositories")

#repositories()

#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#http_archive(
#)

#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#http_archive(
#    name = "com_google_protobuf",
#    sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
#    strip_prefix = "protobuf-3.5.0",
#    urls = ["https://github.com/google/protobuf/archive/v3.5.0.zip"],
#)

#http_archive(
#   name = "com_google_grpc",
#   sha256 = "cef7f1b5a7c5fba672bec2a319246e8feba471f04dcebfe362d55930ee7c1c30",
#   strip_prefix = "protobuf-3.5.0",
#  urls = ["https://github.com/google/protobuf/archive/v3.5.0.zip"],
#)

#http_archive(
#    name = "com_github_grpc_grpc",
#    urls = [
#        "https://github.com/grpc/grpc/archive/512ab8679bf60f321ce133db3323307f7b11504c.tar.gz",
#    ],
#    strip_prefix = "grpc-512ab8679bf60f321ce133db3323307f7b11504c",
#)

#load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
#grpc_deps()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_stack_rules_proto",
    urls = ["https://github.com/stackb/rules_proto/archive/4c2226458203a9653ae722245cc27e8b07c383f7.tar.gz"],
#    sha256 = "{ARCHIVE_TAR_GZ_SHA256}",
    strip_prefix = "rules_proto-4c2226458203a9653ae722245cc27e8b07c383f7",
)

load("@build_stack_rules_proto//cpp:deps.bzl", "cpp_grpc_compile")

cpp_grpc_compile()

http_archive(
    name = "com_github_grpc_grpc",
#    sha256 = "6d4d6640ca3121620995ee255945161821218752b551a1a180f4215f7d124d45",
    urls = [
        "https://github.com/grpc/grpc/archive/512ab8679bf60f321ce133db3323307f7b11504c.tar.gz",
    ],
    strip_prefix = "grpc-512ab8679bf60f321ce133db3323307f7b11504c",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
